# Generated by Django 2.1.3 on 2019-01-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='单位名称')),
                ('level', models.CharField(blank=True, max_length=40, null=True, verbose_name='单位级别')),
                ('seq', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='排序号')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_problem.Department', verbose_name='上级单位')),
            ],
            options={
                'verbose_name': '单位列表',
                'verbose_name_plural': '单位列表',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspect_date', models.DateField(auto_now=True, verbose_name='检查时间')),
                ('name_leader', models.CharField(max_length=60, verbose_name='带队领导')),
                ('name', models.CharField(max_length=60, verbose_name='检查人')),
                ('context_praise', models.TextField(verbose_name='好的方面')),
                ('context_criticize', models.TextField(verbose_name='存在不足')),
                ('flag_show', models.BooleanField(verbose_name='是否显示')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inspect_depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_problem.Department', verbose_name='受检单位')),
            ],
            options={
                'verbose_name': '检查情况汇总表',
                'verbose_name_plural': '检查情况汇总表',
                'ordering': ['inspect_date'],
            },
        ),
    ]
