# Generated by Django 2.1.3 on 2019-01-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('DONE', '已整改'), ('DOING', '已采取措施'), ('UNDO', '未整改')], default='UNDO', max_length=40, verbose_name='是否整改'),
        ),
    ]
