# Generated by Django 2.1.3 on 2019-01-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_problem', '0002_problem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='color_code',
            field=models.CharField(default='red', max_length=20),
        ),
    ]
