# Generated by Django 2.1.3 on 2019-01-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_problem', '0004_auto_20190105_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='color_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
