# Generated by Django 2.1.3 on 2019-01-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_problem', '0005_auto_20190105_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='color_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
