# Generated by Django 2.1.3 on 2019-01-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_problem', '0007_auto_20190105_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('已整改', '已整改'), ('已采取措施', '已采取措施'), ('未整改', '未整改'), ('待查', '待查')], default='未整改', max_length=40, verbose_name='是否整改'),
        ),
    ]
