# Generated by Django 2.1.3 on 2019-01-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_problem', '0009_problem_context_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution_reported',
            field=models.TextField(default='暂无', verbose_name='责任单位上报整改措施'),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_reported_date',
            field=models.DateField(blank=True, null=True, verbose_name='整改措施上报时间'),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_reported_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='上报人'),
        ),
    ]
