# Generated by Django 2.1.3 on 2019-01-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_problem', '0010_auto_20190106_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
