# Generated by Django 2.1.3 on 2019-01-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_problem', '0011_problemchart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemchart',
            options={'verbose_name': '问题汇总展示图表', 'verbose_name_plural': '问题汇总展示图表'},
        ),
    ]
