# Generated by Django 2.1.3 on 2019-01-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_problem', '0012_auto_20190106_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['inspect_date'], 'verbose_name': '检查情况登记表', 'verbose_name_plural': '检查情况登记表'},
        ),
        migrations.AddField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('good', '好的方面'), ('bad', '存在问题')], default='', max_length=20),
        ),
    ]
