# Generated by Django 2.1.3 on 2019-02-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_problem', '0013_auto_20190108_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('good', '好的方面'), ('bad', '存在问题')], default='', max_length=20, verbose_name='类别'),
        ),
    ]
